### ISSUE TITLE
O campo de busca Search Tainacan não permite submeter

### ISSUE THREAD

**Issue by PaulinhoVieira** [Nocs-lab/Obatala#100]
@anaclrra o @Everbero implementou apenas a lógica para a busca dos itens Tainacan, falta definir o comportamento do botão para salvar os dados selecionados, o campo só retorna o objeto com a lista de itens ou coleções.

**Comment by PaulinhoVieira** [comment]
@anaclrra você que está trabalhando diretamente com este componente pode implementar este recurso por favor?

**Comment by anaclrra** [comment]
Implementação realizada. PR aberto: #103
