### ISSUE TITLE
Alteração no nível de acesso dos processos

### ISSUE THREAD

**Issue by PaulinhoVieira** [Nocs-lab/Obatala#99]
Atualmente, a propriedade `AccessLevel` está sendo armazenada como um array, gravada novamente como array, o que resulta em um objeto serializado.

[Link para o código](https://github.com/Nocs-lab/Obatala/blob/857f9d8bea63e905a1124092c2ca25cfaa6f4f5b/src/admin/components/ProcessManager/ProcessCreator.js#L14)

-> @fabiorochafg, o @Everbero sugeriu que poderíamos usar a propriedade de direito de acesso diretamente do próprio `wp_post` em vez de manipulá-la como array. Precisamos da sua opinião sobre essa abordagem: **devemos migrar o acesso para o `wp_post` ou manter o padrão atual?**

Por favor, compartilhe suas recomendações para definirmos o próximo passo.
![imagem_2024-11-04_212647021](https://github.com/user-attachments/assets/2d46719b-4334-42ff-8be7-70866fec5765)

**Comment by anaclrra** [comment]
Implementação realizada. PR aberto: #104
